CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220728190828_InitialProductDbContext') THEN
    CREATE TABLE "Categories" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(50) NOT NULL,
        "Created" timestamp without time zone NULL DEFAULT (NOW()),
        CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220728190828_InitialProductDbContext') THEN
    CREATE TABLE "Products" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(150) NOT NULL,
        "Price" numeric(10,2) NULL,
        "Description" character varying(500) NULL,
        "ImageUrl" character varying(300) NULL,
        "ProductType" text NULL,
        "Created" timestamp without time zone NULL DEFAULT (NOW()),
        "CategoryId" bigint NULL,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220728190828_InitialProductDbContext') THEN
    INSERT INTO "Categories" ("Id", "Name")
    VALUES (1, 'General');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220728190828_InitialProductDbContext') THEN
    INSERT INTO "Products" ("Id", "CategoryId", "Description", "ImageUrl", "Name", "Price", "ProductType")
    VALUES (1, 1, ' This project is a good learning project to get comfortable with soldering and programming an Arduino.', 'https://user-images.githubusercontent.com/41929050/61567048-13938600-aa33-11e9-9cfd-712191013192.jpeg', 'The Quantified Cactus = An Easy Plant Soil Moisture Sensor', 19.9, NULL);
    INSERT INTO "Products" ("Id", "CategoryId", "Description", "ImageUrl", "Name", "Price", "ProductType")
    VALUES (2, 1, ' Use craft items you have around the house, plus two LEDs and a LilyPad battery holder, to create a useful book light for reading in the dark.', 'https://user-images.githubusercontent.com/41929050/61567049-13938600-aa33-11e9-9c69-a4184bf8e524.jpeg', 'A beautiful switch-on book light', 19.9, NULL);
    INSERT INTO "Products" ("Id", "CategoryId", "Description", "ImageUrl", "Name", "Price", "ProductType")
    VALUES (3, 1, ' Create a web-connected light-strip API controllable from your website, using the Particle.io.', 'https://user-images.githubusercontent.com/41929050/61567053-13938600-aa33-11e9-9780-104fe4019659.png', 'Bling your Laptop with an Internet-Connected Light Show', 19.9, NULL);
    INSERT INTO "Products" ("Id", "CategoryId", "Description", "ImageUrl", "Name", "Price", "ProductType")
    VALUES (4, 1, ' Use an Altoids tin with Chibitronics sticker LEDs to create a light-up compact that doubles as a survival kit for the young hipster', 'https://user-images.githubusercontent.com/41929050/61567051-13938600-aa33-11e9-8ae7-0b5c19aafab4.jpeg', 'Create a Compact Survival Kit with LED Track Lighting', 19.9, NULL);
    INSERT INTO "Products" ("Id", "CategoryId", "Description", "ImageUrl", "Name", "Price", "ProductType")
    VALUES (5, 1, ' Visualization of sailor scouts sorted by bubblesort algorithm by their planet''s distance from the sun', 'https://user-images.githubusercontent.com/41929050/61567054-13938600-aa33-11e9-9163-eec98e239b7a.png', 'Bubblesort Visualization', 19.9, NULL);
    INSERT INTO "Products" ("Id", "CategoryId", "Description", "ImageUrl", "Name", "Price", "ProductType")
    VALUES (6, 1, ' Light-up corsage I made with my summer intern.', 'https://user-images.githubusercontent.com/41929050/61567055-142c1c80-aa33-11e9-96ff-9fbac6413625.png', 'Light-up Corsage', 19.9, NULL);
    INSERT INTO "Products" ("Id", "CategoryId", "Description", "ImageUrl", "Name", "Price", "ProductType")
    VALUES (7, 1, ' Pastel hardware kits complete with custom manufactured pastel alligator clips.', 'https://user-images.githubusercontent.com/41929050/61567056-142c1c80-aa33-11e9-8682-10065d338145.png', 'Pastel hardware kit', 19.9, NULL);
    INSERT INTO "Products" ("Id", "CategoryId", "Description", "ImageUrl", "Name", "Price", "ProductType")
    VALUES (8, 1, ' custom molded heart shaped LED with sprinkles.', 'https://user-images.githubusercontent.com/41929050/61567052-13938600-aa33-11e9-9a88-cd842073ba44.jpg', 'Heart-shaped LED', 19.9, NULL);
    INSERT INTO "Products" ("Id", "CategoryId", "Description", "ImageUrl", "Name", "Price", "ProductType")
    VALUES (9, 1, ' Black sweatshirt hoody with the Sick of the Internet logo.', 'https://user-images.githubusercontent.com/41929050/61567060-142c1c80-aa33-11e9-8188-5a4803844a9e.png', 'Black Sweatshirt', 19.9, NULL);
    INSERT INTO "Products" ("Id", "CategoryId", "Description", "ImageUrl", "Name", "Price", "ProductType")
    VALUES (10, 1, ' Still some time to enter the pin/sticker giveaway! ', 'https://user-images.githubusercontent.com/41929050/61567059-142c1c80-aa33-11e9-939b-2ecf4492786d.png', 'Sick of the Internet Pins', 19.9, NULL);
    INSERT INTO "Products" ("Id", "CategoryId", "Description", "ImageUrl", "Name", "Price", "ProductType")
    VALUES (11, 1, ' Hipster Dev is busy coding away while styled in a camo jacket and orange beanie.', 'https://user-images.githubusercontent.com/41929050/61567061-14c4b300-aa33-11e9-9fee-63ff2c0c9823.png', 'Hipster Dev', 19.9, NULL);
    INSERT INTO "Products" ("Id", "CategoryId", "Description", "ImageUrl", "Name", "Price", "ProductType")
    VALUES (12, 1, ' Everyone’s favorite design is finally here on a tee! The Pretty Girls Code crew-neck tee is available in a soft pink with red writing.', 'https://user-images.githubusercontent.com/41929050/61567062-14c4b300-aa33-11e9-9dcd-8bfed4ece810.png', 'Pretty Girls Code Tee', 19.9, NULL);
    INSERT INTO "Products" ("Id", "CategoryId", "Description", "ImageUrl", "Name", "Price", "ProductType")
    VALUES (13, 1, ' Styled in a dashiki, Ruby Sis is listening to music while coding in her favorite language, Ruby!', 'https://user-images.githubusercontent.com/41929050/61567063-14c4b300-aa33-11e9-8515-bcb866da9ea3.png', 'Ruby Sis', 19.9, NULL);
    INSERT INTO "Products" ("Id", "CategoryId", "Description", "ImageUrl", "Name", "Price", "ProductType")
    VALUES (14, 1, ' Not sure if I''ll be making more, get it while I have it in the store.', 'https://user-images.githubusercontent.com/41929050/61567057-142c1c80-aa33-11e9-9781-9e442418eaab.png', 'Holographic Dark Moon Necklace', 19.9, NULL);
    INSERT INTO "Products" ("Id", "CategoryId", "Description", "ImageUrl", "Name", "Price", "ProductType")
    VALUES (15, 1, ' Used up the Diskette fabric today to make 2 of these crops.', 'https://user-images.githubusercontent.com/41929050/61567058-142c1c80-aa33-11e9-89fb-b4f30d84d69d.png', 'Floppy Crop', 19.9, NULL);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220728190828_InitialProductDbContext') THEN
    CREATE UNIQUE INDEX "IX_Categories_Name" ON "Categories" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220728190828_InitialProductDbContext') THEN
    CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220728190828_InitialProductDbContext') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Categories"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Categories") + 1,
            nextval(pg_get_serial_sequence('"Categories"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Products"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Products") + 1,
            nextval(pg_get_serial_sequence('"Products"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220728190828_InitialProductDbContext') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20220728190828_InitialProductDbContext', '6.0.7');
    END IF;
END $EF$;
COMMIT;

