// <auto-generated />
using System;
using GeekShooping.Product.API.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeekShopping.Product.API.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20220802020503_InitialProductDbContext")]
    partial class InitialProductDbContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeekShooping.Product.API.Model.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "General"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Geek"
                        });
                });

            modelBuilder.Entity("GeekShooping.Product.API.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("ProductType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            Description = " This project is a good learning project to get comfortable with soldering and programming an Arduino.",
                            ImageUrl = "https://user-images.githubusercontent.com/41929050/61567048-13938600-aa33-11e9-9cfd-712191013192.jpeg",
                            Name = "The Quantified Cactus = An Easy Plant Soil Moisture Sensor",
                            Price = 19.9m,
                            ProductType = "Resale"
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 1L,
                            Description = " Use craft items you have around the house, plus two LEDs and a LilyPad battery holder, to create a useful book light for reading in the dark.",
                            ImageUrl = "https://user-images.githubusercontent.com/41929050/61567049-13938600-aa33-11e9-9c69-a4184bf8e524.jpeg",
                            Name = "A beautiful switch-on book light",
                            Price = 19.9m,
                            ProductType = "Resale"
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 1L,
                            Description = " Create a web-connected light-strip API controllable from your website, using the Particle.io.",
                            ImageUrl = "https://user-images.githubusercontent.com/41929050/61567053-13938600-aa33-11e9-9780-104fe4019659.png",
                            Name = "Bling your Laptop with an Internet-Connected Light Show",
                            Price = 19.9m,
                            ProductType = "Resale"
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = 1L,
                            Description = " Use an Altoids tin with Chibitronics sticker LEDs to create a light-up compact that doubles as a survival kit for the young hipster",
                            ImageUrl = "https://user-images.githubusercontent.com/41929050/61567051-13938600-aa33-11e9-8ae7-0b5c19aafab4.jpeg",
                            Name = "Create a Compact Survival Kit with LED Track Lighting",
                            Price = 19.9m,
                            ProductType = "Resale"
                        },
                        new
                        {
                            Id = 5L,
                            CategoryId = 1L,
                            Description = " Visualization of sailor scouts sorted by bubblesort algorithm by their planet's distance from the sun",
                            ImageUrl = "https://user-images.githubusercontent.com/41929050/61567054-13938600-aa33-11e9-9163-eec98e239b7a.png",
                            Name = "Bubblesort Visualization",
                            Price = 19.9m,
                            ProductType = "Resale"
                        },
                        new
                        {
                            Id = 6L,
                            CategoryId = 1L,
                            Description = " Light-up corsage I made with my summer intern.",
                            ImageUrl = "https://user-images.githubusercontent.com/41929050/61567055-142c1c80-aa33-11e9-96ff-9fbac6413625.png",
                            Name = "Light-up Corsage",
                            Price = 19.9m,
                            ProductType = "Resale"
                        },
                        new
                        {
                            Id = 7L,
                            CategoryId = 1L,
                            Description = " Pastel hardware kits complete with custom manufactured pastel alligator clips.",
                            ImageUrl = "https://user-images.githubusercontent.com/41929050/61567056-142c1c80-aa33-11e9-8682-10065d338145.png",
                            Name = "Pastel hardware kit",
                            Price = 19.9m,
                            ProductType = "Resale"
                        },
                        new
                        {
                            Id = 8L,
                            CategoryId = 1L,
                            Description = " custom molded heart shaped LED with sprinkles.",
                            ImageUrl = "https://user-images.githubusercontent.com/41929050/61567052-13938600-aa33-11e9-9a88-cd842073ba44.jpg",
                            Name = "Heart-shaped LED",
                            Price = 19.9m,
                            ProductType = "Resale"
                        },
                        new
                        {
                            Id = 9L,
                            CategoryId = 1L,
                            Description = " Black sweatshirt hoody with the Sick of the Internet logo.",
                            ImageUrl = "https://user-images.githubusercontent.com/41929050/61567060-142c1c80-aa33-11e9-8188-5a4803844a9e.png",
                            Name = "Black Sweatshirt",
                            Price = 19.9m,
                            ProductType = "Resale"
                        },
                        new
                        {
                            Id = 10L,
                            CategoryId = 1L,
                            Description = " Still some time to enter the pin/sticker giveaway! ",
                            ImageUrl = "https://user-images.githubusercontent.com/41929050/61567059-142c1c80-aa33-11e9-939b-2ecf4492786d.png",
                            Name = "Sick of the Internet Pins",
                            Price = 19.9m,
                            ProductType = "Resale"
                        },
                        new
                        {
                            Id = 11L,
                            CategoryId = 1L,
                            Description = " Hipster Dev is busy coding away while styled in a camo jacket and orange beanie.",
                            ImageUrl = "https://user-images.githubusercontent.com/41929050/61567061-14c4b300-aa33-11e9-9fee-63ff2c0c9823.png",
                            Name = "Hipster Dev",
                            Price = 19.9m,
                            ProductType = "Resale"
                        },
                        new
                        {
                            Id = 12L,
                            CategoryId = 1L,
                            Description = " Everyone’s favorite design is finally here on a tee! The Pretty Girls Code crew-neck tee is available in a soft pink with red writing.",
                            ImageUrl = "https://user-images.githubusercontent.com/41929050/61567062-14c4b300-aa33-11e9-9dcd-8bfed4ece810.png",
                            Name = "Pretty Girls Code Tee",
                            Price = 19.9m,
                            ProductType = "Resale"
                        },
                        new
                        {
                            Id = 13L,
                            CategoryId = 1L,
                            Description = " Styled in a dashiki, Ruby Sis is listening to music while coding in her favorite language, Ruby!",
                            ImageUrl = "https://user-images.githubusercontent.com/41929050/61567063-14c4b300-aa33-11e9-8515-bcb866da9ea3.png",
                            Name = "Ruby Sis",
                            Price = 19.9m,
                            ProductType = "Resale"
                        },
                        new
                        {
                            Id = 14L,
                            CategoryId = 1L,
                            Description = " Not sure if I'll be making more, get it while I have it in the store.",
                            ImageUrl = "https://user-images.githubusercontent.com/41929050/61567057-142c1c80-aa33-11e9-9781-9e442418eaab.png",
                            Name = "Holographic Dark Moon Necklace",
                            Price = 19.9m,
                            ProductType = "Resale"
                        },
                        new
                        {
                            Id = 15L,
                            CategoryId = 1L,
                            Description = " Used up the Diskette fabric today to make 2 of these crops.",
                            ImageUrl = "https://user-images.githubusercontent.com/41929050/61567058-142c1c80-aa33-11e9-89fb-b4f30d84d69d.png",
                            Name = "Floppy Crop",
                            Price = 19.9m,
                            ProductType = "Resale"
                        });
                });

            modelBuilder.Entity("GeekShooping.Product.API.Model.Product", b =>
                {
                    b.HasOne("GeekShooping.Product.API.Model.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
